title: "EDAM Portfolio"
description: "A research software and ontology integration portfolio"
url: "https://rioualen.github.io"
baseurl: "/edam-portfolio"  # must match repo name

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Author and social info (optional)
author:
  name: "Your Name"
  avatar: "/assets/images/avatar.png"
  bio: "Research Software Engineer"
  location: "France"

# Output portfolio items
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single

