title: "The EDAM ontology"
description: "Portfolio of projects involving the EDAM ontology."
url: "https://rioualen.github.io"
baseurl: "/edam-portfolio-mm"  # must match repo name

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Author and social info (optional)
author:
  name: "Claire Rioualen"
  avatar: "/assets/images/avatar.png"
  bio: "Research Engineer"
  location: "Marseille, France"

# Output portfolio items
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

sass:
  style: compressed
  
defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      css: "main"
      layout: single

