title: "The EDAM ontology"
description: "Portfolio of projects involving the EDAM ontology."
url: "https://rioualen.github.io"
baseurl: "/edam-portfolio-mm"  # must match repo name
logo: "/assets/images/EDAM_square.png"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji

# Author and social info (optional)
author:
  name: "Claire Rioualen"
  avatar: "/assets/images/avatar.png"
  bio: "Research Engineer"
  location: "Marseille, France"

# Output portfolio items
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  docs:
    output: true
    permalink: /docs/:path/

# Enable sidebar nav
show_sidebar: true

  
defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      css: "main"
      layout: single
  - scope:
      path: ""
      type: docs
    values:
      css: "main"
      layout: single